import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    sampleBlogCards:[
        {blogTitle:"Blog Card #1", blogCoverPhoto:"stock-1", blogDate:"May 1, 2022"},
        {blogTitle:"Blog Card #2", blogCoverPhoto:"stock-2", blogDate:"May 2, 2022"},
        {blogTitle:"Blog Card #3", blogCoverPhoto:"stock-3", blogDate:"May 3, 2022"},
        {blogTitle:"Blog Card #4", blogCoverPhoto:"stock-4", blogDate:"May 4, 2022"},
    ],
    CardList:[
      {
        pageLink:'xzc',
        activelink:true,
        title:'Climate Change',
        img:'images/sdg/13.png',
        description:'Reduce GHG Emissions by 10% in 2023',
        mode:'',
        value:'70%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Water Consumption',
        img:'images/sdg/13.png',
        description:'Reduce Water Consumption by 7.25% in 2022',
        mode:'warning',
        value:'53%',
        colors:'progress-new2',
        progress:'Delayed',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Energy Reduction',
        img:'images/sdg/13.png',
        description:'Reduce use of non-renewable energy by 20% by 2025',
        mode:'',
        value:'80%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Diversity & Inclusion',
        img:'images/sdg/13.png',
        description:'Reduce gap in employee count by category by 30 % by 2025',
        mode:'',
        value:'80%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Pay Equality',
        img:'images/sdg/13.png',
        description:'Reduce gap in pay by category by 50% by 2024',
        mode:'',
        value:'80%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Involuntary Labor',
        img:'images/sdg/13.png',
        description:'Reduce risk of involuntary labor by moving production or supply chain by 10 % by 2023',
        mode:'',
        value:'80%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Employee Health and Safety',
        img:'images/sdg/13.png',
        description:'Reduce severe incidents by ...% by year 2025 and increase training access by 10 % ... by 2025',
        mode:'warning',
        value:'10%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Ethical Behavior',
        img:'images/sdg/13.png',
        description:' Reduce loss (stealing or litigation cost) from unethical events by 10% by year 2025 and Increase ethics awareness training access by ...% by year 2025, develop access to channels to report unethical behavior by 10% by 2025',
        mode:'',
        value:'80%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
      {
        pageLink:'xzc',
        activelink:false,
        title:'Waste Reduction',
        img:'images/sdg/13.png',
        description:' Reduce waste sent for disposal by 10%, by 2025, reduce hazardous waste generated by 8 % by 2025 and increase circularity by recycling and design changes etc. by 10% by year 2025',
        mode:'',
        value:'80%',
        colors:'',
        progress:'On-Track',
        status:'Active',
      },
    ],
    GeneratedReportsList:[
      {
          id:'546',
          name:'GRI - 2021',
          description:'Report', 
          standard:'GRI', 
          period:'2021',
          template:'RT-45',
          created:'Mark',
          createdDate:'08/17/2022',                    
      },
      {
          id:'785',
          name:'GRI - 2021',
          description:'Report', 
          standard:'GRI', 
          period:'2021',
          template:'RT-45',
          created:'Mark',
          createdDate:'08/17/2022',                    
      },
      {
          id:'675',
          name:'GRI - 2021',
          description:'Report – Jason', 
          standard:'GRI', 
          period:'2021',
          template:'RT-45',
          created:'Mark',
          createdDate:'08/17/2022',                    
      },
  ],
    editPost:null,
    videos:[
      {  
        id:1,      
        name:'Boy, Christian',
        description:'Name given to Leonardi Di Caprio in the film ‘ Gangs of New York',
        thumbnail:'https://cdn.pixabay.com/photo/2018/08/26/23/55/woman-3633737__480.jpg'
      },
      {
        id:2,
        name:'Thour',
        description:'In Sanskrit it means warrior',
        thumbnail:'https://thumbs.dreamstime.com/b/yellow-crash-test-dummy-yellow-crash-test-dummy-car-seat-116968697.jpg'
      },
      {
        id:3,
        name:'Prince of parcia',
        description:'In Jewish it denotes ‘Angel of Death',
        thumbnail:'https://static.toiimg.com/photo/msid-92996124/92996124.jpg'
      },   
      {     
        id:4,   
        name:'Boy, Christian',
        description:'Name given to Leonardi Di Caprio in the film ‘ Gangs of New York',
        thumbnail:'https://cdn.pixabay.com/photo/2018/08/26/23/55/woman-3633737__480.jpg'
      },
      {
        id:5,
        name:'Thour',
        description:'In Sanskrit it means warrior',
        thumbnail:'https://thumbs.dreamstime.com/b/yellow-crash-test-dummy-yellow-crash-test-dummy-car-seat-116968697.jpg'
      },
      {
        id:6,
        name:'Prince of parcia',
        description:'In Jewish it denotes ‘Angel of Death',
        thumbnail:'https://static.toiimg.com/photo/msid-92996124/92996124.jpg'
      },   
    ],
    ReportTemplatesList:[
        {
            id:255,
            name:'Template For GRI -1',
            description:'Template based on comments from mark', 
            standard:'GRI',                    
        },
        {
            id:256,
            name:'Template For GRI -1',
            description:'Template based on comments from mark', 
            standard:'GRI',                    
        },
    ],
  },
  getters: {
  },
  mutations: {
    toggleEditPost(state, payload){
      state.editPost = payload;
      console.log(state.editPost)
    }
  },
  actions: {
  },
  modules: {
  }
})
